local ok, wk = pcall(require, "which-key")
if not ok then
  return
end

wk.setup({
  preset = "classic",
  delay = 300,
  notify = true,
  plugins = {
    marks = true,
    registers = true,
    spelling = {
      enabled = true,
      suggestions = 20,
    },
    presets = {
      operators = true,
      motions = true,
      text_objects = true,
      windows = true,
      nav = true,
      z = true,
      g = true,
    },
  },
  win = {
    border = "rounded",
    no_overlap = true,
  },
})

wk.add({
  { "<leader>?", function() wk.show({ global = true }) end, desc = "Show keymaps" },
  { "<leader>a", desc = "Toggle Aerial" },
  { "<leader>b", desc = "Toggle breakpoint" },
  { "<leader>B", desc = "Conditional breakpoint" },
  { "<leader>c", group = "Code" },
  { "<leader>ca", desc = "Code action" },
  { "<leader>cp", desc = "File explorer" },
  { "<leader>d", group = "Debug" },
  { "<leader>db", desc = "Open DBUI" },
  { "<leader>di", desc = "DAP step into" },
  { "<leader>du", desc = "DAP toggle UI" },
  { "<leader>e", desc = "Line diagnostics" },
  { "<leader>g", group = "Git / Go" },
  { "<leader>gB", desc = "Toggle line blame" },
  { "<leader>gD", desc = "Diff previous revision" },
  { "<leader>gM", desc = "Gomod scaffold full" },
  { "<leader>gb", desc = "Blame line" },
  { "<leader>gd", desc = "Diff current file" },
  { "<leader>gh", group = "Git Hunk" },
  { "<leader>ghS", desc = "Stage buffer" },
  { "<leader>ghr", desc = "Reset buffer" },
  { "<leader>ghs", desc = "Stage hunk" },
  { "<leader>gi", desc = "Gomod init" },
  { "<leader>gm", desc = "Gomod fill" },
  { "<leader>gp", desc = "Preview hunk" },
  { "<leader>gr", desc = "Reset hunk" },
  { "<leader>gs", desc = "Git status" },
  { "<leader>gu", desc = "Undo stage hunk" },
  { "<leader>h", group = "Harpoon" },
  { "<leader>ha", desc = "Add file" },
  { "<leader>hm", desc = "Menu" },
  { "<leader>hn", desc = "Next file" },
  { "<leader>hp", desc = "Previous file" },
  { "<leader>p", group = "Search" },
  { "<leader>pf", desc = "Find files" },
  { "<leader>ps", desc = "Grep string" },
  { "<leader>r", desc = "Run current file" },
  { "<leader>R", desc = "Run custom command" },
  { "<leader>rn", desc = "Rename symbol" },
  { "<leader>t", desc = "Toggle runner terminal" },
  { "<leader>tf", desc = "Run file tests" },
  { "<leader>td", desc = "Run project tests" },
  { "<leader>to", desc = "Open test output" },
  { "<leader>tp", desc = "Toggle test output panel" },
  { "<leader>ts", desc = "Toggle test summary" },
  { "<leader>tt", desc = "Run nearest test" },
  { "<leader>tS", desc = "Stop tests" },
  { "<leader>u", desc = "Undotree" },
})
